server.port: 3333

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/teemo;AUTO_SERVER=TRUE
    username: sa
      
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.hbm2ddl.auto: create
    showSql: false
    properties:
      hibernate.format_sql: true
      

# Logging
logging:
  config: classpath:logging-config.xml